# Generated by Django 5.2 on 2026-05-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الالكتروني')),
                ('phonenumber', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('major', models.CharField(max_length=100, verbose_name='التخصص')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
    ]
